name: FlightSchool
version: '0.01-alpha'
main: com.a3v1k.flightSchool.platform.paper.FlightSchool
api-version: '1.21'
depend:
  - CreatorSplashCore
commands:
  fsh:
    description: Main command for the FlightSchool game
    usage: /<command> [subcommand]
    permission: fsh.ops
  fsh-test:
    description: yap
    permission: fsh.ops
